version: '2.0'

services:
  drupal:
    image: drupal:latest
    ports:
      - 80:80
    volumes:
      - modules:/var/www/html/modules
      - profiles:/var/www/html/profiles
      - themes:/var/www/html/themes
      - sites:/var/www/html/sites
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: yolo123

volumes:
  modules:
  profiles:
  themes:
  sites:
